# Generated by Django 3.0.8 on 2020-08-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_logic', '0002_auto_20200819_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['number'], 'verbose_name': 'Подсказка', 'verbose_name_plural': 'Подсказки'},
        ),
        migrations.CreateModel(
            name='UserHintPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hint_pair', to='bot_logic.Hint', verbose_name='Подсказка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hint_pair', to='bot_logic.Student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запрошенная студентом подсказка',
                'verbose_name_plural': 'Запрошенные студентами подсказки',
            },
        ),
    ]
