# Generated by Django 3.0.8 on 2020-07-24 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3)),
                ('contest_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='bot_logic.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TestRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.SmallIntegerField(default=3)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_counter', to='bot_logic.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_counter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('test_file', models.FileField(upload_to='tests_files/')),
                ('problem_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='bot_logic.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='sprint_number',
            field=models.ForeignKey(default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem', to='bot_logic.Sprint'),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('problem_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint', to='bot_logic.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='sprint_number',
            field=models.ForeignKey(default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest', to='bot_logic.Sprint'),
        ),
    ]
